### PR TITLE
Updated implementation of global footer to better match RH Site

### PR DESCRIPTION
**Pull request by savannahmccoy**
* Imported part of the [pre-compiled decanter v6 base css](https://github.com/SU-SWS/stanford_basic/blob/8.x/dist/css/base.css) as new file called `decanter css`
* Created custom element component to use Shadow DOM to apply `decanter.css` to only the footer
* Changed default sizing units in decanter css from `em` to `rem` to fix scale issue

### CODE REVIEW

**Comment by alexstorer** [comment]
I'm seeing scrollbar issues in the header

**Comment by alexstorer** [comment]
image

**Comment by Jeffotter** [comment]
Unable to recreate Alex's error, lgtm

**Review by Jeffotter — APPROVED** [review]
The changes look good, worried about the level of JS

**Pull request merged**
